#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <windows.h>
#include <Mmsystem.h>
#include <time.h>
#include <signal.h>
#pragma comment(lib,"winmm.lib")